GET http://localhost:8080/person/1 HTTP/1.1


###

POST http://localhost:8080/person
Content-Type: application/json

{
  "first_name": "2",
  "last_name": "Vasiliev",
  "patronymic": "vasilievich",
  "login": "vaya3",
  "role_id": 3,
  "passwd": "12345678",
  "updated_at": "2020-12-02T15:15:15Z",
  "deleted": false
}

###