services:
  pg:
    image: postgres
    container_name: gus_postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./pg-volume:/var/lib/postgresql
    ports:
      - "5432:5432"