services:
  pg:
    image: postgres
    container_name: gus_postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    volumes:
      - ./pg-volume:/var/lib/postgresql
    ports:
      - "5432:5432"